### ISSUE TITLE
Supplimentary challenge error in question  a(12) != 34012224

### ISSUE THREAD

**Issue by Andati** [SCICodeJam/5yrCodeJam#1]
I believe a(12) != 34012224. 

a(12) is 17210368
a(13) is the 34012224

Here are the first 13 special numbers:
[81, 512, 2401, 4913, 5832, 17576, 19683, 234256, 390625, 614656, 1679616, 17210368, 34012224]

Please check, I might be wrong.

**Comment by denisKaranja** [comment]
Ooh yes! You are right. Thanks for noticing. Correcting in a bit.

**Comment by ProfNandaa** [comment]
Hey @denisKaranja did you correct it, please do and push. Thanks @Andati for raising this...
