### ISSUE TITLE
push rights please ? 

### ISSUE THREAD

**Issue by shimanyi** [SCICodeJam/5yrCodeJam#2]

**Comment by denisKaranja** [comment]
Granted bro.

**Comment by denisKaranja** [comment]
Get the new invite as an owner

**Comment by ProfNandaa** [comment]
So guys we are ready to do this? Let's schedule the #CodeBit meeting early next week, over to you @denisKaranja, you are the boss!

**Comment by shimanyi** [comment]
Alright! @Denis 'with a single n' keep me posted.

Regards,

​
-------------------------------
​

*Shimanyi Valentino Osoro *
Developer - Sisitech Inc <http://sisitech.com/>.
25420 - 00603
KENYA.

|www.sisitech.com | www.c4dlab.ac.ke <http://www.deveint.com/> |

**Comment by denisKaranja** [comment]
Wewe @shimanyi si ulikanywa kutumia (@)Denis hehe

**Comment by shimanyi** [comment]
I keep  forgetting bro. This replies to github chat? Came to me as a mail
notifier

**Comment by denisKaranja** [comment]
Yes, if its an issue raised on Github

**Comment by shimanyi** [comment]
Lesson learnt
